-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua

-- vim.api.nvim_create_autocmd({ "BufReadPost" }, {
-- 	group = vim.api.nvim_create_augroup("tiny-inline", {}),
-- 	callback = function(event)
-- 		vim.diagnostic.config({
-- 			underline = false,
-- 			virtual_text = false,
-- 			update_in_insert = false,
-- 			severity_sort = true,
-- 			signs = {
-- 				text = {
-- 					[vim.diagnostic.severity.ERROR] = " ",
-- 					[vim.diagnostic.severity.WARN] = " ",
-- 					[vim.diagnostic.severity.HINT] = " ",
-- 					[vim.diagnostic.severity.INFO] = " ",
-- 				},
-- 			},
-- 		})
--
-- 		vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
-- 			virtual_text = false,
-- 		})
-- 	end,
-- })
